version: 2
jobs:
  test:
    docker:
      - image: node:8.11.2-slim

    working_directory: ~/repo

    steps:
      - run:
          name: install git
          command: apt update && apt install -y git

      - checkout

      - add_ssh_keys:
          fingerprints:
            - "64:0a:fe:68:ae:b1:69:ec:eb:37:57:97:66:35:a6:2e"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: lint
          command: yarn run lint

      - run:
          name: test
          command: yarn test

  publish:
    docker:
      - image: node:8.11.2-slim

    working_directory: ~/repo

    steps:
      - run:
          name: install git
          command: apt update && apt install -y git
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "64:0a:fe:68:ae:b1:69:ec:eb:37:57:97:66:35:a6:2e"
      - run:
          name: Add npmrc into project directory
          command: echo "${JFROG_NPMRC_BASE64}" | base64 -d > .npmrc
      - run:
          name: npm publish and add tag (only when version updated)
          command: ~/repo/.circleci/publish-and-tagging.sh

workflows:
  version: 2
  per-commit:
    jobs:
      - test
      - publish:
          requires:
            - test
          context: org-global
          filters:
            branches:
              only: master
