version: 2
jobs:
  test:
    docker:
      - image: node:8.11.2-slim

    working_directory: ~/repo

    steps:
      - run:
          name: install git
          command: apt update && apt install -y git

      - checkout

      - add_ssh_keys:
          fingerprints:
            - "64:0a:fe:68:ae:b1:69:ec:eb:37:57:97:66:35:a6:2e"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: npm test

workflows:
  version: 2
  per-commit:
    jobs:
      - test
